version: "2"
linters:
  enable:
    - errorlint
    - forbidigo
    - godot
    - misspell
    - revive
    - testifylint
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
    godot:
      exclude:
        # Ignore "See: URL".
        - 'See:'
      capital: true
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/procfs
