---
linters:
  enable:
  - errcheck
  - forbidigo
  - godot
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - testifylint
  - unused

linter-settings:
  forbidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: Do not commit print statements.
  godot:
    capital: true
    exclude:
    # Ignore "See: URL"
    - 'See:'
  goimports:
      local-prefixes: github.com/prometheus/procfs
  misspell:
    locale: US
