version: "2"
linters:
  enable:
    - errorlint
    - forbidigo
    - gocritic
    - godot
    - misspell
    - revive
    - testifylint
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
    gocritic:
      enable-all: true
      disabled-checks:
        - commentFormatting
        - commentedOutCode
        - deferInLoop
        - emptyStringTest
        - filepathJoin
        - hugeParam
        - ifElseChain
        - importShadow
        - paramTypeCombine
        - rangeValCopy
        - regexpSimplify
        - sloppyReassign
        - stringsCompare
        - stringXbytes
        - tooManyResultsChecker
        - unnamedResult
        - whyNoLint
    godot:
      exclude:
        # Ignore "See: URL".
        - 'See:'
      capital: true
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/procfs
